### ISSUE TITLE
Boolean writing error on Influx V2

### ISSUE THREAD

**Issue by ferreroboema** [coussej/node-opcua-logger#77]
Hello,

I'm currently testing this tool with Influx V2 (dev branch), everything seems to work fine with floating values, but I can't make the boolean values work and I get the following error: 

```
[2022-03-03T15:06:54.059] [WARN] influx - failure writing points to database: partial write: field type conflict: input field "value" on measurement "Monitored" is type boolean, already exists as type float dropped=1
false [Function: bound booleanField]
ERROR: Write to InfluxDB failed. d [HttpError]: failure writing points to database: partial write: field type conflict: input field "value" on measurement "Monitored" is type boolean, already exists as type float dropped=1
```

Any suggestion?

Thanks,

Luca

**Comment by coussej** [comment]
Hello Luca,

you seem to already have a measurement named 'Monitored' in the database,
either because you previously had a float measurement in the config file,
or you have a double entry somewhere.

If you check the config file for errors and it is OK, you can just drop the
measurement monitored (DROP MEASUREMENT "Monitored") in influxdb and it
will be recreated as boolean.

**Comment by ferreroboema** [comment]
My error, I guess I have misunderstood the measurment field.
Thank you very much for the answer and for this amazing tool.

Luca
